[package]
name = "roguelike_engine"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34", features = ["image", "unsafe_textures"] }

serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_yaml = "0.8"

slotmap = "0.4"

noise = { version = "0.6", default-features = false }

rexpaint = "*"

symbol = "0.1"

mint = "0.5.1"

log = "0.4"
simple-logging = "2.0"

rand = {version = "0.7.0", default-features = false, features = ["small_rng", "std"] }

roguelike_core = { path = "../roguelike_core" }
